on:
  pull_request:
    types: [opened, synchronize]
jobs:
  test:
    name: ğŸ— Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: ğŸ— Cache Node Modules
        uses: actions/cache@v2
        env:
          cache-name: ğŸ— cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-   
            ${{ runner.os }}-build- 
            ${{ runner.os }}-
      - name: ğŸ“¦ Install Packages
        run: yarn
      # Peform a type check if you are using typescript
      - name: ğŸš€ Typecheck
        run: yarn tsc
      - name: ğŸš€ Check Lint
        run: yarn lintFix
